"""House B — The Oracle.

House B does NOT improve ideas. It redefines the problem entirely.
Given vague human input, House B consults the KnowledgeGraph and a
cloud LLM (Mistral AI) to produce a StructuredSpecificationObject
that captures what the problem *actually* is, along with a
MinorityReport that anticipates every way the plan could fail.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any

from nexus.core.belief_certificate import BeliefCertificate
from nexus.core.knowledge_graph import KnowledgeGraph
from nexus.core.model_router import ModelRouter
from nexus.core.skill_library import SkillLibrary
from nexus.core.counterfactual import CounterfactualEntry, CounterfactualLog, groq_counterfactual_alternatives
from nexus.core.domain_normalizer import normalize_domain

logger: logging.Logger = logging.getLogger(__name__)

_MAX_RETRIES: int = 1


def _normalize_three_success_criteria(
    raw: Any,
    redefined_problem: str,
) -> list[str]:
    """Ensure exactly three measurable success criteria for the SSO."""
    out: list[str] = []
    if isinstance(raw, list):
        for x in raw:
            if isinstance(x, str) and x.strip():
                out.append(x.strip()[:500])
    filler = [
        f"Automated tests pass for the implementation implied by: {redefined_problem[:120]}",
        "No unhandled exceptions on representative valid and edge-case inputs",
        "Public API matches the specified signatures and return types in the task",
    ]
    while len(out) < 3:
        out.append(filler[len(out) % len(filler)])
    return out[:3]

# ------------------------------------------------------------------
# System prompts
# ------------------------------------------------------------------

HOUSE_B_SYSTEM: str = (
    "You are NEXUS House B. Your job is not to answer questions. "
    "Your job is to understand what problem is ACTUALLY being asked, "
    "which is almost never what the human said.\n"
    "You have access to verified knowledge. Use it.\n"
    "Return ONLY valid JSON. No explanation. No markdown.\n\n"
    "The JSON must have exactly these keys:\n"
    '  "redefined_problem": string,\n'
    '  "assumptions": [string, ...],\n'
    '  "constraints": [string, ...],\n'
    '  "success_criteria": EXACTLY 3 strings — each must be a MEASURABLE,\n'
    "    testable criterion (what pytest or a human can verify), e.g.\n"
    '    \"function returns True for valid input\", not vague goals.\n'
    '  "required_inputs": [string, ...],\n'
    '  "expected_outputs": [string, ...],\n'
    '  "domain": string,\n'
    '  "confidence": float (0.0 to 1.0)\n'
)

HOUSE_D_SYSTEM: str = (
    "You are House D — the destroyer. Find reasons this plan will fail. "
    "Return a JSON object with exactly these 4 keys:\n"
    "- reasons_to_fail: list of 2 strings maximum\n"
    "- risks: list of 2 strings maximum\n"
    "- hidden_assumptions: list of 2 strings maximum\n"
    "- better_alternatives: list of 1 string maximum\n\n"
    "Keep each string under 100 characters.\n"
    "Return ONLY the JSON object."
)


# ------------------------------------------------------------------
# Dataclasses
# ------------------------------------------------------------------

@dataclass
class MinorityReport:
    """Adversarial analysis of why a plan will fail.

    Generated by a separate LLM call acting as House D — the
    destroyer. Every SSO must carry a MinorityReport so that no
    plan reaches execution without its weaknesses exposed.

    Attributes:
        reasons_to_fail: Concrete reasons the plan will not succeed.
        risks: Things that can go wrong during execution.
        hidden_assumptions: Assumptions embedded in the plan that
            were never explicitly stated.
        better_alternatives: Alternative approaches that may be
            superior to the proposed plan.
    """

    reasons_to_fail: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    hidden_assumptions: list[str] = field(default_factory=list)
    better_alternatives: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a plain dictionary."""
        return {
            "reasons_to_fail": list(self.reasons_to_fail),
            "risks": list(self.risks),
            "hidden_assumptions": list(self.hidden_assumptions),
            "better_alternatives": list(self.better_alternatives),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MinorityReport:
        """Reconstruct from a dictionary.

        Args:
            data: Dictionary with MinorityReport fields.

        Returns:
            A hydrated MinorityReport instance.
        """
        return cls(
            reasons_to_fail=data.get("reasons_to_fail", []),
            risks=data.get("risks", []),
            hidden_assumptions=data.get("hidden_assumptions", []),
            better_alternatives=data.get("better_alternatives", []),
        )


@dataclass
class StructuredSpecificationObject:
    """The output of House B — a redefined, structured problem spec.

    An SSO is never returned without a completed MinorityReport
    attached. Together they ensure downstream Houses receive a
    precise specification *and* a premortem analysis.

    Attributes:
        original_input: The raw human input that triggered this SSO.
        redefined_problem: What the problem actually is, as
            determined by House B and the knowledge graph.
        assumptions: Assumptions House B is making.
        constraints: Hard limits on the solution space.
        success_criteria: Measurable criteria for success.
        required_inputs: Data or resources needed to begin.
        expected_outputs: What the solution should produce.
        domain: Knowledge domain this problem falls under.
        confidence: House B's confidence in its redefinition (0-1).
        minority_report: Adversarial analysis from House D.
    """

    original_input: str
    redefined_problem: str
    assumptions: list[str] = field(default_factory=list)
    constraints: list[str] = field(default_factory=list)
    success_criteria: list[str] = field(default_factory=list)
    required_inputs: list[str] = field(default_factory=list)
    expected_outputs: list[str] = field(default_factory=list)
    domain: str = "General"
    confidence: float = 0.5
    minority_report: MinorityReport = field(default_factory=MinorityReport)

    def to_dict(self) -> dict[str, Any]:
        """Serialise the full SSO including its MinorityReport."""
        return {
            "original_input": self.original_input,
            "redefined_problem": self.redefined_problem,
            "assumptions": list(self.assumptions),
            "constraints": list(self.constraints),
            "success_criteria": list(self.success_criteria),
            "required_inputs": list(self.required_inputs),
            "expected_outputs": list(self.expected_outputs),
            "domain": self.domain,
            "confidence": self.confidence,
            "minority_report": self.minority_report.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> StructuredSpecificationObject:
        """Reconstruct from a dictionary.

        Args:
            data: Dictionary with SSO fields.

        Returns:
            A fully hydrated SSO with MinorityReport.
        """
        mr_data = data.get("minority_report", {})
        return cls(
            original_input=data["original_input"],
            redefined_problem=data["redefined_problem"],
            assumptions=data.get("assumptions", []),
            constraints=data.get("constraints", []),
            success_criteria=data.get("success_criteria", []),
            required_inputs=data.get("required_inputs", []),
            expected_outputs=data.get("expected_outputs", []),
            domain=data.get("domain", "General"),
            confidence=data.get("confidence", 0.5),
            minority_report=MinorityReport.from_dict(mr_data),
        )


# ------------------------------------------------------------------
# House B — The Oracle
# ------------------------------------------------------------------

@dataclass
class HouseB:
    """The Oracle — redefines problems rather than answering them.

    House B takes raw human input, consults the KnowledgeGraph for
    relevant verified beliefs, and uses a cloud LLM (Mistral AI)
    to produce a StructuredSpecificationObject. A second LLM call
    generates the MinorityReport (adversarial premortem).

    Attributes:
        knowledge_graph: The shared NEXUS knowledge store.
        router: ModelRouter for LLM calls.
    """

    knowledge_graph: KnowledgeGraph
    router: ModelRouter = field(default_factory=ModelRouter)
    skill_library: SkillLibrary | None = None
    counterfactual_log: CounterfactualLog | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def redefine(self, user_input: str, *, cycle_id: str = "") -> StructuredSpecificationObject:
        """Redefine a problem from raw human input.

        Queries the knowledge graph for domain-relevant beliefs,
        builds a context-enriched prompt, calls the LLM to produce
        a structured redefinition, then generates a MinorityReport
        via a separate adversarial LLM call.

        Args:
            user_input: The raw, unstructured human request.

        Returns:
            A complete StructuredSpecificationObject with an attached
            MinorityReport. Never returns an SSO without one.

        Raises:
            ValueError: If the LLM fails to return valid JSON after
                one retry.
        """
        start = time.perf_counter()
        logger.info("HOUSE-B redefine started  input=%r", user_input[:120])

        knowledge_context = self._build_knowledge_context("General")

        system = HOUSE_B_SYSTEM
        if self.skill_library:
            tools_text = self.skill_library.inject_into_prompt(user_input, max_k=3)
            if tools_text:
                system = system + "\n\nYou have these verified tools available:\n" + tools_text

        user_prompt = (
            f"Human input:\n{user_input}\n\n"
            f"Verified knowledge from the graph:\n{knowledge_context}\n\n"
            "Now redefine this problem. Return ONLY the JSON object."
        )

        raw = self._call_llm(
            system=system,
            user=user_prompt,
            label="redefine",
        )

        parsed = self._parse_json(raw, label="redefine")

        rp = parsed.get("redefined_problem", user_input)
        sc = _normalize_three_success_criteria(
            parsed.get("success_criteria", []),
            rp,
        )
        sso = StructuredSpecificationObject(
            original_input=user_input,
            redefined_problem=rp,
            assumptions=parsed.get("assumptions", []),
            constraints=parsed.get("constraints", []),
            success_criteria=sc,
            required_inputs=parsed.get("required_inputs", []),
            expected_outputs=parsed.get("expected_outputs", []),
            domain=parsed.get("domain", "General"),
            confidence=float(parsed.get("confidence", 0.5)),
        )

        sso.minority_report = self._generate_minority_report(sso)

        if self.counterfactual_log and cycle_id:
            rejected = groq_counterfactual_alternatives(user_input, sso.redefined_problem)
            if rejected:
                self.counterfactual_log.add_entry(
                    CounterfactualEntry(
                        cycle_id=cycle_id,
                        house="house_b",
                        chosen_action=sso.redefined_problem[:1500],
                        rejected_candidates=rejected,
                        actual_outcome="",
                        was_prediction_correct=None,
                    )
                )

        elapsed = time.perf_counter() - start
        logger.info(
            "HOUSE-B redefine complete  domain=%r  confidence=%s  elapsed=%.2fs",
            sso.domain, sso.confidence, elapsed,
        )
        return sso

    # ------------------------------------------------------------------
    # Public — Refine SSO based on House D attacks
    # ------------------------------------------------------------------

    def refine(
        self,
        sso: StructuredSpecificationObject,
        destruction_report: Any,
    ) -> StructuredSpecificationObject:
        """Refine an SSO that was attacked by House D.

        Takes the original SSO and the DestructionReport containing
        the attacks, then asks the LLM to produce an improved SSO
        that addresses the specific flaws found.

        Args:
            sso: The SSO that failed House D review.
            destruction_report: The DestructionReport with attack details.

        Returns:
            A new, refined SSO with an attached MinorityReport.

        Raises:
            ValueError: If the LLM fails to return valid JSON after
                one retry.
        """
        start = time.perf_counter()
        logger.info(
            "HOUSE-B refine started  problem=%r",
            sso.redefined_problem[:80],
        )

        attacks_summary = "\n".join(
            f"- [{a.attack_type}] (severity={a.severity}, fatal={a.is_fatal}) "
            f"{a.description}"
            for a in destruction_report.attacks
        ) or "(no specific attacks)"

        knowledge_context = self._build_knowledge_context(sso.domain)

        user_prompt = (
            f"The following specification was REJECTED by House D.\n\n"
            f"Original problem: {sso.redefined_problem}\n"
            f"Assumptions: {json.dumps(sso.assumptions)}\n"
            f"Constraints: {json.dumps(sso.constraints)}\n"
            f"Success criteria: {json.dumps(sso.success_criteria)}\n"
            f"Domain: {sso.domain}\n\n"
            f"House D attacks:\n{attacks_summary}\n\n"
            f"Verified knowledge:\n{knowledge_context}\n\n"
            f"Refine the specification to address EVERY attack above. "
            f"Return ONLY the JSON object."
        )

        raw = self._call_llm(
            system=HOUSE_B_SYSTEM,
            user=user_prompt,
            label="refine",
        )

        parsed = self._parse_json(raw, label="refine")

        rp2 = parsed.get("redefined_problem", sso.redefined_problem)
        sc2 = _normalize_three_success_criteria(
            parsed.get("success_criteria", sso.success_criteria),
            rp2,
        )
        refined = StructuredSpecificationObject(
            original_input=sso.original_input,
            redefined_problem=rp2,
            assumptions=parsed.get("assumptions", sso.assumptions),
            constraints=parsed.get("constraints", sso.constraints),
            success_criteria=sc2,
            required_inputs=parsed.get("required_inputs", sso.required_inputs),
            expected_outputs=parsed.get("expected_outputs", sso.expected_outputs),
            domain=parsed.get("domain", sso.domain),
            confidence=float(parsed.get("confidence", sso.confidence)),
        )

        refined.minority_report = self._generate_minority_report(refined)

        elapsed = time.perf_counter() - start
        logger.info(
            "HOUSE-B refine complete  domain=%r  confidence=%s  elapsed=%.2fs",
            refined.domain, refined.confidence, elapsed,
        )
        return refined

    # ------------------------------------------------------------------
    # Private — Minority Report
    # ------------------------------------------------------------------

    def _generate_minority_report(
        self, sso: StructuredSpecificationObject,
    ) -> MinorityReport:
        """Generate an adversarial MinorityReport for the given SSO.

        Makes a separate LLM call acting as House D — the destroyer.

        Args:
            sso: The StructuredSpecificationObject to attack.

        Returns:
            A MinorityReport listing failure modes, risks, hidden
            assumptions, and better alternatives.

        Raises:
            ValueError: If the LLM fails to return valid JSON after
                one retry.
        """
        start = time.perf_counter()

        user_prompt = (
            f"Plan to evaluate:\n"
            f"  Problem: {sso.redefined_problem}\n"
            f"  Assumptions: {json.dumps(sso.assumptions)}\n"
            f"  Constraints: {json.dumps(sso.constraints)}\n"
            f"  Success criteria: {json.dumps(sso.success_criteria)}\n"
            f"  Domain: {sso.domain}\n\n"
            "Destroy this plan. Return ONLY the JSON object."
        )

        raw = self._call_llm(
            system=HOUSE_D_SYSTEM,
            user=user_prompt,
            label="minority_report",
        )

        parsed = self._parse_json(raw, label="minority_report")

        report = MinorityReport(
            reasons_to_fail=parsed.get("reasons_to_fail", []),
            risks=parsed.get("risks", []),
            hidden_assumptions=parsed.get("hidden_assumptions", []),
            better_alternatives=parsed.get("better_alternatives", []),
        )

        elapsed = time.perf_counter() - start
        logger.info(
            "HOUSE-D minority report complete  "
            "failure_reasons=%d  risks=%d  elapsed=%.2fs",
            len(report.reasons_to_fail), len(report.risks), elapsed,
        )
        return report

    # ------------------------------------------------------------------
    # Private — Knowledge context
    # ------------------------------------------------------------------

    def _build_knowledge_context(self, domain: str) -> str:
        """Build context from domain-relevant, non-axiom beliefs only (FIX 6).

        Founding axioms (``is_axiom``) never appear — they were skewing
        House B (e.g. kill switch). Only beliefs whose normalized domain
        matches the task domain are included.

        Args:
            domain: Primary domain (e.g. from SSO).

        Returns:
            Up to 5 top beliefs by confidence, or a fallback when empty.
        """
        nd = normalize_domain(domain)

        def _base_ok(b: BeliefCertificate) -> bool:
            if getattr(b, "is_axiom", False):
                return False
            if not b.is_valid() or b.is_expired():
                return False
            if getattr(b, "quarantined", False):
                return False
            return True

        pool: list[BeliefCertificate] = []
        seen: set[str] = set()

        if nd == "General":
            for b in sorted(
                self.knowledge_graph.beliefs_snapshot(),
                key=lambda x: x.confidence,
                reverse=True,
            ):
                if not _base_ok(b):
                    continue
                pool.append(b)
                if len(pool) >= 5:
                    break
        else:

            def _same_domain(b: BeliefCertificate) -> bool:
                return _base_ok(b) and normalize_domain(b.domain) == nd

            for b in self.knowledge_graph.query_domain(domain):
                if not _same_domain(b):
                    continue
                pool.append(b)
                seen.add(b.claim)

            if len(pool) < 5:
                for b in self.knowledge_graph.beliefs_snapshot():
                    if b.claim in seen or not _same_domain(b):
                        continue
                    pool.append(b)
                    seen.add(b.claim)
                    if len(pool) >= 5:
                        break

        top = sorted(pool, key=lambda b: b.confidence, reverse=True)[:5]

        if not top:
            return "(no verified knowledge available)"

        lines: list[str] = []
        for i, b in enumerate(top, 1):
            lines.append(
                f"{i}. [{b.domain}] (confidence={b.confidence}) {b.claim}"
            )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Private — LLM calls
    # ------------------------------------------------------------------

    def _call_llm(self, system: str, user: str, label: str) -> str:
        """Route an LLM call through the ModelRouter.

        Args:
            system: The system prompt.
            user: The user prompt.
            label: A human-readable label for logging.

        Returns:
            The raw text content from the LLM response.
        """
        return self.router.complete(
            house="house_b", system=system, user=user, label=label,
        )

    def _parse_json(self, raw: str, label: str) -> dict[str, Any]:
        """Parse a JSON string from LLM output with resilient fallbacks.

        Handles markdown fences, extracted JSON objects, and truncated JSON.

        Args:
            raw: The raw string that should be valid JSON.
            label: A label used in log and error messages.

        Returns:
            The parsed dictionary.

        Raises:
            ValueError: If parsing fails after all repair attempts.
        """
        text = re.sub(r"```json|```", "", raw).strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        try:
            start = text.find("{")
            end = text.rfind("}") + 1
            if start >= 0 and end > start:
                return json.loads(text[start:end])
        except json.JSONDecodeError:
            pass

        try:
            open_braces = text.count("{") - text.count("}")
            open_brackets = text.count("[") - text.count("]")
            repaired = text.rstrip()
            if repaired.endswith(","):
                repaired = repaired[:-1]
            repaired += "]" * max(0, open_brackets)
            repaired += "}" * max(0, open_braces)
            return json.loads(repaired)
        except json.JSONDecodeError:
            pass

        # Truncation inside a string: find last complete string, close structure
        try:
            repaired = text.rstrip()
            last_complete = max(
                (repaired.rfind(m) for m in ('",', '"]', '"\n')),
                default=-1,
            )
            if last_complete < 0:
                # No delimiter after last string; find last complete quoted string
                for m in re.finditer(r'"([^"\\]|\\.)*"', repaired):
                    last_complete = m.end() - 1  # position of closing quote
            if last_complete >= 0:
                truncated = repaired[: last_complete + 1].rstrip().rstrip(",")
                open_brackets = truncated.count("[") - truncated.count("]")
                open_braces = truncated.count("{") - truncated.count("}")
                truncated += "]" * max(0, open_brackets)
                truncated += "}" * max(0, open_braces)
                return json.loads(truncated)
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

        raise ValueError(
            f"House B returned invalid JSON for '{label}' after all attempts. Raw: {raw[:300]}"
        )
